# alias tmux="TERM=xterm-256color tmux"
alias -g C=" | cut"
alias -g G=" | grep"
alias -g L=" | less"
alias -g S=" | sort"
alias -g U=" | uniq"
alias a="vim $cli_tools_dir/aliases.sh"
alias c="clear"
alias cd="cdh"
alias cdd="cd $dist"
alias cdl="cd ~/local_work_dir"
alias e="vim $cli_tools_dir/.zshrc"
alias ea="sudo easy_install"
alias f="vim $cli_tools_dir/functions.sh"
alias gb="git branch | grep"
alias gc!="git commit -v --amend"
alias gc="git commit -v -a"
alias gd="git diff master"
alias gh="history | grep"
alias gp="git pull"
alias gpom="git push origin master"
alias gr="git rebase"
alias grb="git branch -D"
alias gri="git rebase -i"
alias grim="git rebase -i master"
alias grm="git rebase master"
alias gs="git status"
alias h="history | less"
alias i="sudo apt-get install"
alias k="kill -9"
alias l="vim ~/.local_functions"
alias la="ls -AlG --group-directories-first"
alias lt='ls -gAGhslrt --group-directories-first'
alias m="gmt master"
alias pi="pip install"
alias pip="sudo pip"
alias s="cp2h;source ~/.zshrc"
alias sb="source ~/.bashrc"
alias sp="source ~/.bash_profile"
alias v="vim $cli_tools_dir/.vimrc"

#Keep this after git commands

alias st="tmux source-file ~/.tmux.conf"
alias v="vim $cli_tools_dir/.vimrc"
alias -g wl=" | wc -l"
